### ISSUE TITLE
Publish go-sparkplug-primary to dockerhub

### ISSUE THREAD

**Issue by dtq-one** [DATATRONiQ/go-sparkplug-primary#12]
## Background

In order to facilitate adoption of go-sparkplug-primary we want to publish Docker images to dockerhub.com

## Tasks

- [ ] Setup DATATRONiQ on Dockerhub to host public docker images for go-sparkplug-primary
- [ ] Setup Github Action / .github/workflows to build docker images for multiple platforms (x86, aarm64, aarm)
- [ ] Setup Github Action / .github/workflows to publish images to dockerhub
