### ISSUE TITLE
Research and enable various Github Actions (also from Marketplace) to improve code quality, security, and robustness 

### ISSUE THREAD

**Issue by dtq-one** [DATATRONiQ/go-sparkplug-primary#14]
## Background

Github Actions (w/ Marketplace) offer a variety of automated workflows to perform CI actions, such as running tests, code coverage, rebasing of pull requests, dependency checking (of included libraries)

## Tasks

- [ ] Research popular actions for this purpose
  - [ ] marketplace
  - [ ] other Go-based projects
- [ ] Decide what actions/workflows to incorporate
- [ ] Update this issue to include actions/workflows to incorporate
- [ ] Implement most important actions/workflows
